version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5433:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - auction-redis:/var/lib/redis/
  elasticsearch:
    build:
      context: .
      dockerfile: docker/elasticsearch/Dockerfile
    environment:
      - xpack.security.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  auction:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/auction/Dockerfile
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - sidekiq
      - elasticsearch
  sidekiq:
    build:
      context: .
      dockerfile: docker/auction/Dockerfile
    command: bundle exec sidekiq
    depends_on:
      - redis
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    env_file:
      - .env
volumes:
  bundle:
  data-volume:
  auction-redis:
  es-data:
