version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5433:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - auction-redis:/var/lib/redis/
  auction:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - sidekiq-bundle:/usr/local/bundle
    env_file:
      - .env
volumes:
  bundle:
  data-volume:
  auction-redis:
  sidekiq-bundle:
