local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  servide: Disk
  root: <%= Rails.root.join("tmp/storage") %>

# amazon:
#   service: S3
#   access_key_id: ""
#   secret_access_key: ""
#   region: ""
#   bucket: ""
