FROM docker.elastic.co/elasticsearch/elasticsearch:6.3.0

# plugins
RUN elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.3.0/elasticsearch-analysis-ik-6.3.0.zip
